version: '3'
services:
  jenkins:
    image: thiagolsfortunato/mapskills-jenkins:2.60.2
    restart: on-failure
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/mapskills/docker-compose.yml:/mapskills/docker-compose.yml
      - back:/mapskills/back:rw
      - front:/mapskills/front:rw
    environment:
      DOCKER_SOCKET: /var/run/docker.sock
      DOCKER_GROUP: dockerhost
      JENKINS_USER: jenkins
    ports:
      - 8585:8080
  front:
    image: thiagolsfortunato/mapskills-tomcat8:v1
    restart: on-failure
    volumes:
      - front:/usr/local/tomcat/webapps:rw
    ports:
      - 80:8080
  back:
    image: thiagolsfortunato/mapskills-tomcat8:v1
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role != manager]
    volumes:
      - back:/usr/local/tomcat/webapps:rw
  mysql:
    image: thiagolsfortunato/mapskills-mysql:5.6
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "mapskills"
    volumes:
      - mysql:/var/lib/mysql/mapskills
    ports:
      - 3306:3306
  lb:
    image: thiagolsfortunato/mapskills-haproxy:alpine
    restart: on-failure
    environment:
      - STATS_AUTH=mapskills:mapskills
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8080:80
      - 1936:1936
  cadvisor:
    image: thiagolsfortunato/mapskills-cadvisor
    restart: on-failure
    volumes:
      - /:/roofs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8888:8080
networks:
  mapskills:
    driver: overlay
volumes:
  mysql:
  back: {}
  front: {}
