version: '3'
services:
  # Container Jenkins responsável pelo Build e Deploy do Mapskills
  jenkins:
    image: thiagolsfortunato/mapskills-jenkins:2.60.2
    container_name: mapskills-jenkins
    restart: on-failure
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/mapskills/docker-compose.yml:/mapskills/docker-compose.yml
      - back:/mapskills/back:rw
      - front:/mapskills/front:rw
    environment:
      DOCKER_SOCKET: /var/run/docker.sock
      DOCKER_GROUP: dockerhost
      JENKINS_USER: jenkins
    ports:
      - 8585:8080
  # Container Cadvisor responsável por monitorar todo ambiente Docker
  cadvisor:
    image: thiagolsfortunato/mapskills-cadvisor
    container_name: mapskills-cadivisor
    volumes:
      - /:/roofs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8888:8080
  # Container Mysql responsável por armazenar toda Base de Dados Mapskills
  mysql:
    image: thiagolsfortunato/mapskills-mysql:5.6
    container_name: mapskills-mysql
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql/mapskills
    environment:
      MYSQL_ROOT_PASSWORD: mapskills
      MYSQL_DATABASE: mapskills
      MYSQL_USER: mapskills
      MYSQL_PASSWORD: mapskills
    ports:
      - 3306:3306
volumes:
  mysql:
  back: 
  front: