version: '3'
services:
  front:
    image: thiagolsfortunato/mapskills-tomcat8:v1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - manager_front:/usr/local/tomcat/webapps:rw
    networks:
      - overlay
    ports:
      - 80:8080
  back:
    image: thiagolsfortunato/mapskills-tomcat8:v1
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    links:
      - mysql
    networks:
      - overlay
    volumes:
      - manager_back:/usr/local/tomcat/webapps:rw
  mysql:
    image: thiagolsfortunato/mapskills-mysql:5.6
    container_name: mapskills-mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: mapskills
      MYSQL_DATABASE: mapskills
      MYSQL_USER: mapskills
      MYSQL_PASSWORD: mapskills
    networks:
      - overlay
    volumes:
      - mysql:/var/lib/mysql/mapskills
    ports:
      - 3306:3306
  lb:
    image: thiagolsfortunato/mapskills-haproxy:alpine
    container_name: mapskills-haproxy
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - STATS_AUTH=mapskills:mapskills
    links:
      - back
    networks:
      - overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
      - 1936:1936
volumes:
  manager_mysql:
    external: true
  manager_back:
    external: true
  manager_front:
    external: true