version: '3'
volumes:
  mysql:
  back: {}
  front: {}
services:
  jenkins:
    image: thiagolsfortunato/mapskills-jenkins
    restart: always
    volumes:
      - back:/mapskills/back:rw
      - front:/mapskills/front:rw
    environment:
      - /var/run/docker.sock:/var/run/docker.sock
     ports:
      - 8585:8080
  front:
    image: thiagolsfortunato/mapskills-tomcat8:v1
    restart: always
    volumes:
      - front:/usr/local/tomcat/webapps
    ports:
      - 80:8080
  back:
    image: thiagolsfortunato/mapskills-tomcat8:v1
    restart: always
    volumes:
      - back:/usr/local/tomcat/webapps
  mysql:
    image: thiagolsfortunato/mapskills-mysql:v1
    restart: always
    volumes:
      - mysql:/var/lib/mysql/mapskills
    environment:
      MYSQL_ROOT_PASSWORD: "mapskills"
      MYSQL_DATABASE: "mapskills"
      MYSQL_USER: "mapskills"
      MYSQL_PASSWORD: "mapskills"
    ports:
      - 3306:3306
  lb:
    image: thiagolsfortunato/mapskills-haproxy:v1
    restart: always
    environment:
      - STATS_AUTH=mapskills:mapskills
    links:
      - back
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
      - 1936:1936
  cadvisor:
    image: thiagolsfortunato/mapskills-cadvisor
    restart: always
    volumes:
      - /:/roofs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8888:8080